version: "3.7"

services:

  nginx:
    image: nginx:1.19.5
    ports:
      - 80:80
    networks:
      - code_square_network
    volumes:
      - /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf
      - code_square_static:/data/static/
      - code_square_media:/data/media/

  django:
    image: django_deploy4
    networks:
      - code_square_network
    volumes:
      - code_square_static:/home/July5/staticfiles/
      - code_square_media:/home/July5/media/
    secrets:
      - DJANGO_SECRET_KEY


  mariadb:
    image: mariadb:10.5
    networks:
      - code_square_network
    volumes:
      - code_square_mariadb:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: password1234
      MARIADB_DATABASE: django
      MARIADB_USER: django
      MARIADB_PASSWORD: password1234


networks:
  code_square_network:

volumes:
  code_square_static:
  code_square_media:
  code_square_mariadb:

secrets:
  DJANGO_SECRET_KEY:
    external: true