version: "3.7"

services:

  nginx:
    image: nginx:1.19.5
    ports:
      - 80:80
    networks:
      - code_square_network
    volumes:
      - /home/threatsquare/nginx.conf:/etc/nginx/nginx.conf
      - code_square_static:/data/static/
      - code_square_media:/data/media/

  django:
    image: django_deploy5
    networks:
      - code_square_network
    volumes:
      - code_square_static:/home/July5/staticfiles/
      - code_square_media:/home/July5/media/
    secrets:
      - DJANGO_SECRET_KEY
      - MARIADB_USER
      - MARIADB_PASSWORD


  mariadb:
    image: mariadb:10.5
    networks:
      - code_square_network
    volumes:
      - code_square_mariadb:/var/lib/mysql
    secrets:
      - MARIADB_ROOT_PASSWORD
      - MARIADB_USER
      - MARIADB_PASSWORD
    environment:
      MARIADB_DATABASE: django
      MARIADB_USER_FILE: /run/secrets/MARIADB_USER
      MARIADB_PASSWORD_FILE: /run/secrets/MARIADB_PASSWORD
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/MARIADB_ROOT_PASSWORD


networks:
  code_square_network:

volumes:
  code_square_static:
  code_square_media:
  code_square_mariadb:

secrets:
  DJANGO_SECRET_KEY:
    external: true
  MARIADB_ROOT_PASSWORD:
    external: true
  MARIADB_USER:
    external: true
  MARIADB_PASSWORD:
    external: true